#!/bin/bash
sed -i -e '/^env\[DB_/d' /etc/php5/fpm/pool.d/www.conf
env | awk -F= '/^DB_/ {print "env[" $1 "] = $" $1}' >> /etc/php5/fpm/pool.d/www.conf
exec /usr/sbin/php5-fpm --fpm-config /etc/php5/fpm/php-fpm.conf
